<a href="https://colab.research.google.com/github/ianelgar40/IansMIS433/blob/main/python_basics_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Ian
Welcome, Ian!


In [ ]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

f= int(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c= input('Please enter the temperature in Celcius: ')

c= int(c)

#Celsius = (Fahrenheit – 32)*5/9
f = (c * 9/5) + 32
print(f'{c}C is {f} in Fahrenheit. ')

Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

if m == 'C':
    d = int(d)
    f = (d * 9/5) + 32
    print(f'{d}C is {f} in Fahrenheit')
elif m == 'F':
    d = int(d)
    c = (d - 32) * 5/9
    print(f'{d}F is {c} in Celsius')
else:
    print('Invalid input')


Please enter the temperature: 140
Is this in Celsius or Fahrenheit? F
140F is 60.0 in Celsius


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
print(len(sentence))


48


In [ ]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9:-9])

heap. Show me the code - Linus


In [ ]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split(' '))

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().split(' '))


['talk', 'is', 'cheap.', 'show', 'me', 'the', 'code', '-', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
for v in vowels:
    print(v, sentence.lower().count(v))
    ...

a 3
e 4
i 2
o 3
u 1


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
    print(i, sentence[i])
    ...

0 T
1 a
2 l
3 k
4  
5 i
6 s
7  
8 c
9 h
10 e
11 a
12 p
13 .
14  
15 S
16 h
17 o
18 w
19  
20 m
21 e
22  
23 t
24 h
25 e
26  
27 c
28 o
29 d
30 e
31  
32 -
33  
34 L
35 i
36 n
37 u
38 s
39  
40 T
41 o
42 r
43 v
44 a
45 l
46 d
47 s


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i**3)
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes_lc = [i**3 for i in range(5)]
print(cubes_lc)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = 'aeiou'
vowels_lc = [i for i in range(len(sentence)) if sentence[i] in vowels]
print(vowels_lc)



[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')


# add your code here
n = int(n)
a, b = 0, 1
for i in range(n):
    fibonacci.append(a)
    a, b = b, a+b
print(fibonacci)


How many numbers do you want? 20
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {}
v_dict['Pfizer'] = 0.95
v_dict['Moderna'] = 0.95
v_dict['AstraZeneca'] = 0.72
v_dict['Johnson & Johnson'] = 0.66

In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Pfizer
0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914

In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038

In [ ]:
# Print vaccines with efficacy lower than 90%.
print([v for v in v_dict if v_dict[v] < 0.9])

['AstraZeneca', 'Johnson & Johnson', 'Sinovac']


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']

In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
count = 0
for ch in sentence:
    if ch == ' ':
        continue
    if ch in ch_dict:
        ch_dict[ch] += 1
    else:
        ch_dict[ch] = 1
# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [ ]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
even_numbers = np.arange(2, 42, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([])
first_row = np.arange(0, 10)
second_row = np.arange(10, 20)
third_row = np.arange(20, 30)
fourth_row = np.arange(30, 40)
fifth_row = np.arange(40, 50)
sixth_row = np.arange(50, 60)
seventh_row = np.arange(60, 70)
eighth_row = np.arange(70, 80)
ninth_row = np.arange(80, 90)
tenth_row = np.arange(90, 100)
arr = np.array([first_row, second_row, third_row, fourth_row, fifth_row, sixth_row, seventh_row, eighth_row, ninth_row, tenth_row])
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
print(M)

[[ 0.37378118 -1.31671411  1.04944019 -0.4974972  -0.15605397 -1.03343825
   1.28575195  0.96065577  0.17710606 -1.91873291]
 [-1.00391252 -0.43959533  1.87215059 -0.41629896 -0.09954832  0.55283028
   0.44857751  0.53265421  0.34513062  0.14844214]
 [ 0.30350136 -0.06660025  1.48985637  2.07481984  1.44173562 -0.05692888
   0.3280904   1.0223239  -0.71673892 -0.23908489]
 [-0.22525956  0.26470409 -0.59982972  1.13524743  1.03107543  0.0915868
  -0.18868644  0.03389423 -0.12076889 -0.71245088]
 [-0.08105564 -1.17958456 -0.76645066  0.00920743  1.03009735  0.34392409
   0.00913615  0.28797558  0.87299935 -1.8339544 ]
 [-2.16275505 -1.53762587 -2.13087664  1.51424928 -1.59713208  0.99752021
   1.05226046 -1.04653664 -0.37910639 -0.63833714]
 [-0.14543105  1.23792833 -1.26868814 -1.26023687 -0.69440354 -0.65691393
   0.91073132 -1.46625653 -0.35837291 -1.34487712]
 [-0.76500627  0.46253554 -0.06788214  0.82705917  2.29724374 -1.25096306
  -1.37961514 -0.81399363  0.05554556 -1.38761628]
 

In [ ]:
# Count the numbers in M with an absolute value greater than 1.
print(np.sum(np.abs(M) > 1))


39


In [ ]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of rows (input another integer >= 3)
c = int(input('column count: '))

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
arr

Row count: 3
column count: 3


array([[16, 19, 18],
       [12, 19, 14],
       [16, 10, 12]])

In [ ]:
# output the element in the first row and the third column
print(arr[0, 2])

18


In [ ]:
# output the element in the second row and the last column
print(arr[1, 2])

14


In [ ]:
# output the second row of the array
print(arr[1])

[12 19 14]


In [ ]:
# output the second last row of the array
print(arr[1])

[12 19 14]


In [ ]:
# output the second column of the array
print(arr[:, 1])

[19 19 10]


In [ ]:
# output the second last column of the array
print(arr[:, 1])

[19 19 10]


In [ ]:
# output the upper-left 3x3 sub-array
print(arr[0,0])

16


In [ ]:
# output the bottom-left 3x3 sub-array
print(arr[2,0])

16


In [ ]:
# output the upper-right 3x3 sub-array
print(arr[0,2])

18


In [ ]:
# output the bottom-right 3x3 sub-array
print(arr[2,2])

12


In [ ]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = A.reshape(5, 10)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
# add a row [51,...,60] to A
A= np.append(A, np.arange(51, 61).reshape(1, 10), axis=0)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1 = A[:3]
A2 = A[3:]
print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# Add 10 to each element of A
A1 = A1 + 10
print(A1)
A2= A2 + 10
print(A2)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]
[[41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [ ]:
# Calculate the square root of each element in A
A1 = np.sqrt(A1)
print(A1)
A2 = np.sqrt(A2)
print(A2)

[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]]
[[6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [ ]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape


(10, 10)

In [ ]:
# Print the mean, standard devietion of all numbers in M
M.mean()
M.std()

np.float64(1.0187619267464643)

In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(f"Maximum: {np.max(M):.4f}")
print(f"3rd Quartile: {np.percentile(M, 75):.4f}")
print(f"Median: {np.median(M):.4f}")
print(f"1st Quartile: {np.percentile(M, 25):.4f}")
print(f"Minimum: {np.min(M):.4f}")

Maximum: 2.2972
3rd Quartile: 0.4801
Median: -0.0561
1st Quartile: -0.7783
Minimum: -2.9459
